Curation 185 186 attach literature to publication proxy settings
EBISPOT/gwas-curation-service pull request #226
Opened 2024-06-05 07:07 UTC by sprintell

2024-06-05 08:40 UTC, ala-ebi approved these changes

2024-06-05 08:44 UTC, ala-ebi commented on src/main/java/uk/ac/ebi/spot/gwas/curation/service/impl/LiteratureFileServiceImpl.java
>                      .createdBy(user.getEmail())
I think we should also set createDate

2024-06-05 08:58 UTC, sajo-ebi requested changes
Since create date is populated in all Entities we should have it also on literature table. I agree with Ala

2024-06-11 09:15 UTC, ala-ebi approved these changes

2024-06-11 09:35 UTC, merged